enum UserType {
    admin
    client
    technical
}

type User {
    id: ID
    name: String
    lastname: String
    email: String
    username: String
    address: String
    phone_number: String
    password: String
    user_type: UserType
    created_at: String
    updated_at: String
    deleted: Boolean
}

input IntoUser {
    name: String
    lastname: String
    email: String
    username: String
    address: String
    phone_number: String
    password: String
    user_type: UserType
}
